targets:
  $default:
    builders:
      go_router_builder:
        generate_for:
          - "lib/src/router/router.dart"
      riverpod_generator:
        generate_for:
          - "**/application/**.dart"
          - "lib/src/router/router.dart"