targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - "**/application/**.dart"
          - "**/data/**.dart"
          - "lib/src/router/router.dart"
          - "lib/src/utils/shared_preferences.dart"